version: '3'

services:
  api:
    build:
      context: .
    ports:
      - 8000:${API_PORT}
    networks:
      - dockerIsolation
      - default
    env_file:
      - .env
    expose:
      - ${API_PORT}
    depends_on:
      - postgres
    command: node src/app.js

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - dockerIsolation
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_volume:/var/lib/postgresql/data/
volumes:
  db_volume:

networks:
  dockerIsolation:
